### ISSUE TITLE
大佬，求教

### ISSUE THREAD

**Issue by CWZ7605** [nicksun98/R2S-Wiki#14]
我买的是带风扇的R2S。
基于openwrt原版的这个系统，风扇一直都是全速转动。
虽然温度低，但风扇寿命也短很多了。
有没有什么方法让风扇根据温度来改变转速？
friendlywrt倒是有这个功能。
不知大佬是否有办法，求指教。

**Comment by nicholas-opensource** [comment]
群里有办法，问群主。您昵称是？
